# Generated by Django 5.2.5 on 2025-08-31 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_alter_usuario_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usuario",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="username",
        ),
    ]
