# Generated by Django 5.2.5 on 2025-08-21 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Subcategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produtos.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "genero",
                    models.CharField(
                        choices=[
                            ("Feminino", "Feminino"),
                            ("Masculino", "Masculino"),
                            ("Infantil", "Infantil"),
                            ("Unissex", "Unissex"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tamanho",
                    models.CharField(
                        choices=[
                            ("PP", "PP"),
                            ("P", "P"),
                            ("M", "M"),
                            ("G", "G"),
                            ("GG", "GG"),
                            ("36", "36"),
                            ("38", "38"),
                            ("40", "40"),
                            ("42", "42"),
                            ("44", "44"),
                        ],
                        max_length=10,
                    ),
                ),
                ("imagem_principal", models.ImageField(upload_to="produtos/")),
                (
                    "imagem_secundaria",
                    models.ImageField(blank=True, null=True, upload_to="produtos/"),
                ),
                (
                    "imagem_detalhe",
                    models.ImageField(blank=True, null=True, upload_to="produtos/"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="produtos.categoria",
                    ),
                ),
                (
                    "dono",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subcategoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="produtos.subcategoria",
                    ),
                ),
            ],
        ),
    ]
