# Generated by Django 5.2.5 on 2025-09-04 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="Tamanho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="produto",
            name="tamanho",
        ),
        migrations.AddField(
            model_name="produto",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="estoque",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="produto",
            name="marca",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="produtos.marca",
            ),
        ),
        migrations.CreateModel(
            name="ProdutoImagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="produtos/")),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="produtos.produto",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem"],
            },
        ),
        migrations.AddField(
            model_name="produto",
            name="tamanhos",
            field=models.ManyToManyField(blank=True, to="produtos.tamanho"),
        ),
    ]
