# Generated by Django 5.2.5 on 2025-09-06 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "produtos",
            "0003_marca_tamanho_remove_produto_tamanho_produto_ativo_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EstoqueTamanho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=0)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estoque_tamanhos",
                        to="produtos.produto",
                    ),
                ),
                (
                    "tamanho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="produtos.tamanho",
                    ),
                ),
            ],
            options={
                "unique_together": {("produto", "tamanho")},
            },
        ),
    ]
