# Generated by Django 5.2.5 on 2025-09-06 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0005_popula_marcas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="dono",
        ),
    ]
